# Generated by Django 4.2 on 2026-02-06 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目的地名称')),
                ('city', models.CharField(max_length=50, verbose_name='所在城市')),
                ('region', models.CharField(max_length=50, verbose_name='所在地区')),
                ('description', models.TextField(verbose_name='目的地描述')),
                ('category', models.CharField(choices=[('natural', '自然景观'), ('cultural', '文化古迹'), ('leisure', '休闲娱乐'), ('adventure', '冒险体验'), ('shopping', '购物天堂')], max_length=50, verbose_name='目的地类型')),
                ('rating', models.FloatField(verbose_name='评分')),
                ('review_count', models.IntegerField(verbose_name='评论数量')),
                ('price_level', models.CharField(choices=[('low', '低消费'), ('medium', '中等消费'), ('high', '高消费')], max_length=20, verbose_name='消费水平')),
                ('popular_season', models.CharField(max_length=100, verbose_name='最佳旅游季节')),
                ('visitor_volume', models.IntegerField(verbose_name='年游客量')),
                ('facilities', models.JSONField(verbose_name='设施服务')),
                ('tags', models.JSONField(verbose_name='标签')),
                ('coordinates', models.JSONField(verbose_name='坐标')),
                ('images', models.JSONField(verbose_name='图片链接')),
            ],
            options={
                'verbose_name': '旅游目的地',
                'verbose_name_plural': '旅游目的地',
            },
        ),
        migrations.CreateModel(
            name='DestinationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50, verbose_name='特征名称')),
                ('feature_value', models.FloatField(verbose_name='特征值')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.destination', verbose_name='关联目的地')),
            ],
            options={
                'verbose_name': '目的地特征',
                'verbose_name_plural': '目的地特征',
            },
        ),
    ]