# Generated by Django 4.2

from django.db import migrations
import json


def add_initial_destinations(apps, schema_editor):
    Destination = apps.get_model('destination', 'Destination')
    
    destinations_data = [
        {
            'name': '故宫博物院',
            'city': '北京',
            'region': '华北',
            'description': '中国明清两代的皇家宫殿，位于北京中轴线的中心，是中国古代宫廷建筑之精华，也是世界上现存规模最大、保存最为完整的木质结构古建筑之一。',
            'category': 'cultural',
            'rating': 4.9,
            'review_count': 12580,
            'price_level': 'medium',
            'popular_season': '春秋两季（4-5月、9-10月）',
            'visitor_volume': 19000000,
            'facilities': ['停车场', '餐厅', '纪念品商店', '语音导览', '轮椅通道', '母婴室'],
            'tags': ['文化古迹', '历史', '世界遗产', '必去景点'],
            'coordinates': {'lat': 39.9163, 'lon': 116.3972},
            'images': ['https://images.unsplash.com/photo-1508804052814-cd3ba865a116?w=800']
        },
        {
            'name': '长城',
            'city': '北京',
            'region': '华北',
            'description': '中国古代伟大的防御工程，被誉为世界七大奇迹之一，是中华民族的象征，承载着数千年的历史与文化。',
            'category': 'cultural',
            'rating': 4.8,
            'review_count': 15230,
            'price_level': 'medium',
            'popular_season': '春秋两季（4-5月、9-10月）',
            'visitor_volume': 10000000,
            'facilities': ['索道', '滑车', '观景台', '休息区', '小卖部'],
            'tags': ['文化古迹', '历史', '世界遗产', '户外运动'],
            'coordinates': {'lat': 40.4319, 'lon': 116.5704},
            'images': ['https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800']
        },
        {
            'name': '西湖',
            'city': '杭州',
            'region': '华东',
            'description': '中国著名的风景名胜区，以秀丽的湖光山色和众多的名胜古迹闻名于世，被誉为人间天堂。',
            'category': 'natural',
            'rating': 4.7,
            'review_count': 18920,
            'price_level': 'low',
            'popular_season': '春季（3-4月）和秋季（9-11月）',
            'visitor_volume': 28000000,
            'facilities': ['游船', '自行车租赁', '茶室', '餐厅', '公园座椅'],
            'tags': ['自然景观', '湖泊', '世界遗产', '免费景点'],
            'coordinates': {'lat': 30.2428, 'lon': 120.1489},
            'images': ['https://images.unsplash.com/photo-1598887142485-6e6f0d1b1b5f?w=800']
        },
        {
            'name': '黄山',
            'city': '黄山',
            'region': '华东',
            'description': '中国著名的山岳风景区，以奇松、怪石、云海、温泉四绝著称于世，是世界文化与自然双重遗产。',
            'category': 'natural',
            'rating': 4.9,
            'review_count': 9870,
            'price_level': 'medium',
            'popular_season': '夏季（6-8月）和秋季（9-11月）',
            'visitor_volume': 3500000,
            'facilities': ['缆车', '酒店', '餐厅', '索道', '观景台'],
            'tags': ['自然景观', '山岳', '世界遗产', '户外运动'],
            'coordinates': {'lat': 30.1333, 'lon': 118.1750},
            'images': ['https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800']
        },
        {
            'name': '外滩',
            'city': '上海',
            'region': '华东',
            'description': '上海著名的旅游景点，位于黄浦江畔，是上海最具代表性的城市景观区域，汇集了众多历史建筑和现代摩天大楼。',
            'category': 'leisure',
            'rating': 4.6,
            'review_count': 21560,
            'price_level': 'high',
            'popular_season': '全年皆宜',
            'visitor_volume': 20000000,
            'facilities': ['观光隧道', '游船', '餐厅', '购物商场', '公共厕所'],
            'tags': ['城市景观', '建筑', '夜景', '免费景点'],
            'coordinates': {'lat': 31.2401, 'lon': 121.4901},
            'images': ['https://images.unsplash.com/photo-1537531383496-f4749b608527?w=800']
        }
    ]
    
    for dest_data in destinations_data:
        Destination.objects.create(**dest_data)


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_destinations),
    ]
