# Generated by Django 6.0.2 on 2026-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_add_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='攻略标题')),
                ('category', models.CharField(choices=[('出行准备', '出行准备'), ('行程规划', '行程规划'), ('省钱攻略', '省钱攻略'), ('注意事项', '注意事项')], max_length=50, verbose_name='攻略分类')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('content', models.TextField(verbose_name='攻略内容')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('tags', models.JSONField(verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '旅游攻略',
                'verbose_name_plural': '旅游攻略',
                'ordering': ['-created_at'],
            },
        ),
    ]
