# Generated by Django 4.2

from django.db import migrations


def add_more_destinations(apps, schema_editor):
    Destination = apps.get_model('destination', 'Destination')

    destinations_data = [
        {
            'name': '洪崖洞',
            'city': '重庆',
            'region': '西南',
            'description': '重庆最具代表性的景点，依山而建的吊脚楼建筑群，夜景尤为壮观，是重庆的地标性建筑。',
            'category': 'cultural',
            'rating': 4.7,
            'review_count': 25600,
            'price_level': 'low',
            'popular_season': '全年皆宜',
            'visitor_volume': 15000000,
            'facilities': ['观景台', '餐厅', '纪念品商店', '电梯'],
            'tags': ['文化古迹', '夜景', '吊脚楼', '免费景点', '网红打卡'],
            'coordinates': {'lat': 29.5630, 'lon': 106.5770},
            'images': ['https://images.unsplash.com/photo-1590077428518-3e2d6e8f3d5f?w=800']
        },
        {
            'name': '解放碑',
            'city': '重庆',
            'region': '西南',
            'description': '重庆市中心的标志性建筑，中国西部第一条商业步行街，周围商圈繁华，是购物和美食的天堂。',
            'category': 'leisure',
            'rating': 4.5,
            'review_count': 18900,
            'price_level': 'medium',
            'popular_season': '全年皆宜',
            'visitor_volume': 12000000,
            'facilities': ['购物中心', '餐厅', '地铁站', '停车场'],
            'tags': ['城市景观', '购物', '美食', '地标建筑'],
            'coordinates': {'lat': 29.5565, 'lon': 106.5780},
            'images': ['https://images.unsplash.com/photo-1583425423320-23858f6707a3?w=800']
        },
        {
            'name': '武隆天生三桥',
            'city': '重庆',
            'region': '西南',
            'description': '世界自然遗产，由天龙桥、青龙桥、黑龙桥三座天然石拱桥组成，壮观震撼，是《变形金刚4》取景地。',
            'category': 'natural',
            'rating': 4.8,
            'review_count': 8500,
            'price_level': 'medium',
            'popular_season': '春秋两季（4-5月、9-10月）',
            'visitor_volume': 3000000,
            'facilities': ['观光电梯', '观景台', '休息区', '餐厅'],
            'tags': ['自然景观', '喀斯特地貌', '世界遗产', '户外运动', '电影取景地'],
            'coordinates': {'lat': 29.3667, 'lon': 107.7833},
            'images': ['https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800']
        },
        {
            'name': '广州塔（小蛮腰）',
            'city': '广州',
            'region': '华南',
            'description': '广州地标性建筑，中国第一高塔，塔身线条优美如少女腰肢，夜景璀璨夺目。',
            'category': 'leisure',
            'rating': 4.6,
            'review_count': 22000,
            'price_level': 'high',
            'popular_season': '秋季（10-12月）',
            'visitor_volume': 18000000,
            'facilities': ['观光层', '摩天轮', '餐厅', '纪念品店'],
            'tags': ['城市景观', '地标建筑', '夜景', '摩天轮'],
            'coordinates': {'lat': 23.1060, 'lon': 113.3240},
            'images': ['https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800']
        },
        {
            'name': '陈家祠',
            'city': '广州',
            'region': '华南',
            'description': '广东规模最大、装饰华丽、保存完好的传统岭南祠堂式建筑，被誉为"岭南建筑艺术明珠"。',
            'category': 'cultural',
            'rating': 4.7,
            'review_count': 12000,
            'price_level': 'low',
            'popular_season': '全年皆宜',
            'visitor_volume': 5000000,
            'facilities': ['语音导览', '纪念品商店', '休息区'],
            'tags': ['文化古迹', '岭南建筑', '博物馆', '雕刻艺术'],
            'coordinates': {'lat': 23.1280, 'lon': 113.2580},
            'images': ['https://images.unsplash.com/photo-1548013146-72479768bada?w=800']
        },
        {
            'name': '长隆野生动物世界',
            'city': '广州',
            'region': '华南',
            'description': '中国最大的野生动物园之一，拥有500多种20000多只动物，可近距离观赏各种珍稀动物。',
            'category': 'leisure',
            'rating': 4.8,
            'review_count': 35000,
            'price_level': 'high',
            'popular_season': '全年皆宜',
            'visitor_volume': 10000000,
            'facilities': ['观光车', '餐厅', '儿童游乐区', '纪念品商店'],
            'tags': ['动物园', '亲子游', '动物表演', '主题公园'],
            'coordinates': {'lat': 22.9980, 'lon': 113.3300},
            'images': ['https://images.unsplash.com/photo-1534567110243-e26b2c067291?w=800']
        },
        {
            'name': '深圳世界之窗',
            'city': '深圳',
            'region': '华南',
            'description': '中国著名的微缩景区，汇集了世界各地著名景点的缩影，一日游遍世界的理想选择。',
            'category': 'leisure',
            'rating': 4.5,
            'review_count': 28000,
            'price_level': 'high',
            'popular_season': '全年皆宜',
            'visitor_volume': 12000000,
            'facilities': ['观光车', '餐厅', '表演剧场', '纪念品商店'],
            'tags': ['主题公园', '微缩景观', '世界名胜', '演出表演'],
            'coordinates': {'lat': 22.5350, 'lon': 113.9740},
            'images': ['https://images.unsplash.com/photo-1563514227147-6d5ff5ca9b2b?w=800']
        },
        {
            'name': '大梅沙海滨公园',
            'city': '深圳',
            'region': '华南',
            'description': '深圳最著名的海滩，拥有绵长的金色沙滩和清澈的海水，是休闲度假的好去处。',
            'category': 'natural',
            'rating': 4.4,
            'review_count': 18500,
            'price_level': 'low',
            'popular_season': '夏季（5-10月）',
            'visitor_volume': 8000000,
            'facilities': ['更衣室', '淋浴间', '餐厅', '救生站'],
            'tags': ['海滩', '海滨度假', '免费景点', '水上运动'],
            'coordinates': {'lat': 22.6000, 'lon': 114.3050},
            'images': ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800']
        },
        {
            'name': '锦绣中华民俗村',
            'city': '深圳',
            'region': '华南',
            'description': '中国第一个文化主题公园，展示中国各地的民俗文化和历史遗迹的微缩景观。',
            'category': 'cultural',
            'rating': 4.3,
            'review_count': 15000,
            'price_level': 'medium',
            'popular_season': '全年皆宜',
            'visitor_volume': 6000000,
            'facilities': ['表演剧场', '餐厅', '纪念品商店'],
            'tags': ['文化古迹', '民俗文化', '微缩景观', '演出表演'],
            'coordinates': {'lat': 22.5320, 'lon': 113.9780},
            'images': ['https://images.unsplash.com/photo-1528164344705-47542687000d?w=800']
        },
        {
            'name': '成都大熊猫繁育研究基地',
            'city': '成都',
            'region': '西南',
            'description': '全球最大的大熊猫人工繁育机构，可以近距离观赏可爱的大熊猫，是成都必去的景点。',
            'category': 'natural',
            'rating': 4.8,
            'review_count': 42000,
            'price_level': 'medium',
            'popular_season': '全年皆宜',
            'visitor_volume': 14000000,
            'facilities': ['观光车', '餐厅', '纪念品商店', '母婴室'],
            'tags': ['动物园', '国宝熊猫', '亲子游', '生态保护'],
            'coordinates': {'lat': 30.7380, 'lon': 104.1450},
            'images': ['https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800']
        },
        {
            'name': '宽窄巷子',
            'city': '成都',
            'region': '西南',
            'description': '成都最具代表性的历史文化街区，由宽巷子、窄巷子和井巷子组成，体验老成都的慢生活。',
            'category': 'cultural',
            'rating': 4.6,
            'review_count': 32000,
            'price_level': 'low',
            'popular_season': '全年皆宜',
            'visitor_volume': 16000000,
            'facilities': ['茶馆', '小吃街', '手工艺品店', '民宿'],
            'tags': ['文化古迹', '历史文化', '美食', '慢生活', '免费景点'],
            'coordinates': {'lat': 30.6680, 'lon': 104.0560},
            'images': ['https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800']
        },
        {
            'name': '都江堰',
            'city': '成都',
            'region': '西南',
            'description': '世界上现存最早的无坝引水工程，距今2000多年历史，是世界文化遗产和国家级风景名胜区。',
            'category': 'cultural',
            'rating': 4.7,
            'review_count': 16500,
            'price_level': 'medium',
            'popular_season': '春秋两季（4-5月、9-10月）',
            'visitor_volume': 7000000,
            'facilities': ['观光车', '索道', '餐厅', '观景台'],
            'tags': ['文化古迹', '水利工程', '世界遗产', '历史'],
            'coordinates': {'lat': 30.9980, 'lon': 103.6180},
            'images': ['https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800']
        },
        {
            'name': '兵马俑',
            'city': '西安',
            'region': '西北',
            'description': "世界第八大奇迹，秦始皇陵的陪葬坑，数千个陶俑神态各异，展现了秦朝的军阵威仪。",
            'category': 'cultural',
            'rating': 4.9,
            'review_count': 38000,
            'price_level': 'medium',
            'popular_season': '春秋两季（3-5月、9-11月）',
            'visitor_volume': 9000000,
            'facilities': ['语音导览', '纪念品商店', '餐厅', '停车场'],
            'tags': ['文化古迹', '世界遗产', '历史', '秦始皇', '必去景点'],
            'coordinates': {'lat': 34.3840, 'lon': 109.2780},
            'images': ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800']
        },
        {
            'name': '大唐不夜城',
            'city': '西安',
            'region': '西北',
            'description': '以盛唐文化为主题的大型仿古步行街，夜晚灯光璀璨，仿佛穿越回唐朝长安城。',
            'category': 'leisure',
            'rating': 4.6,
            'review_count': 25000,
            'price_level': 'low',
            'popular_season': '全年皆宜',
            'visitor_volume': 11000000,
            'facilities': ['表演剧场', '餐厅', '小吃街', '文创商店'],
            'tags': ['城市景观', '唐文化', '夜景', '免费景点', '网红打卡'],
            'coordinates': {'lat': 34.2180, 'lon': 108.9640},
            'images': ['https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800']
        },
        {
            'name': '华清宫',
            'city': '西安',
            'region': '西北',
            'description': "唐代皇家温泉行宫，杨贵妃沐浴的地方，背靠骊山，风景秀丽，是中国四大皇家园林之一。",
            'category': 'cultural',
            'rating': 4.5,
            'review_count': 13500,
            'price_level': 'medium',
            'popular_season': '春秋两季（4-5月、9-10月）',
            'visitor_volume': 5000000,
            'facilities': ['温泉', '酒店', '餐厅', '表演剧场'],
            'tags': ['文化古迹', '皇家园林', '温泉', '历史', '唐玄宗与杨贵妃'],
            'coordinates': {'lat': 34.3650, 'lon': 109.2120},
            'images': ['https://images.unsplash.com/photo-1548013146-72479768bada?w=800']
        }
    ]

    for dest_data in destinations_data:
        Destination.objects.create(**dest_data)


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_add_travel_guides_data'),
    ]

    operations = [
        migrations.RunPython(add_more_destinations),
    ]
