# Generated by Django 4.2

from django.db import migrations


def fix_ethnic_category(apps, schema_editor):
    Destination = apps.get_model('destination', 'Destination')

    ethnic_keywords = ['傣族', '白族', '苗族', '侗族', '土家族', '彝族', '藏族',
                      '蒙古族', '朝鲜族', '哈尼族', '羌族', '鄂温克族', '赫哲族',
                      '泼水节', '三道茶', '苗寨', '侗寨', '土司城', '火把节',
                      '梯田', '碉楼', '驯鹿', '渔猎', '鱼皮画', '民俗园']

    leisure_destinations = Destination.objects.filter(category='leisure')

    for dest in leisure_destinations:
        tags_str = str(dest.tags) if dest.tags else ''
        name_str = dest.name
        desc_str = dest.description or ''

        combined_text = f'{name_str} {desc_str} {tags_str}'

        is_ethnic = any(keyword in combined_text for keyword in ethnic_keywords)

        if is_ethnic:
            dest.category = 'ethnic'
            dest.save(update_fields=['category'])


class Migration(migrations.Migration):
    dependencies = [
        ('destination', '0008_add_category_destinations'),
    ]

    operations = [
        migrations.RunPython(fix_ethnic_category),
    ]
