# Generated by Django 6.0.2 on 2026-02-06 15:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('adventure', '冒险型'), ('leisure', '休闲型'), ('cultural', '文化型'), ('nature', '自然型'), ('shopping', '购物型')], max_length=50, null=True, verbose_name='旅游类型偏好'),
        ),
    ]
